os: osx
osx_image:
  - xcode9.4
  - xcode9.3
install: wget https://github.com/yonaskolb/XcodeGen/releases/download/2.3.0/xcodegen.zip && unzip xcodegen.zip && xcodegen/bin/xcodegen
language: objective-c
xcode_project: PrivateProtocolBuffer.xcodeproj
xcode_scheme:
  - PrivateProtocolBuffer ios
  - PrivateProtocolBuffer macos
  - PrivateProtocolBuffer tvos
