os: osx
# osx_image:
#   - xcode9.4
  # - xcode9.3
install: wget https://github.com/yonaskolb/XcodeGen/releases/download/2.3.0/xcodegen.zip && unzip xcodegen.zip && xcodegen/bin/xcodegen
language: objective-c
xcode_project: PrivateProtocolBuffer.xcodeproj
# env:
  # - XCODE_SCHEME="Linked tests ios" DESTINATION="platform=iOS Simulator,name=iPhone 8"
  # - XCODE_SCHEME="Unlinked tests ios" DESTINATION="platform=iOS Simulator,name=iPhone 8"
  # - XCODE_SCHEME="Linked tests tvos" DESTINATION="platform=tvOS Simulator,name=Apple TV"
  # - XCODE_SCHEME="Unlinked tests tvos" DESTINATION="platform=tvOS Simulator,name=Apple TV"
  # - XCODE_SCHEME="Linked tests macos" DESTINATION="platform=macOS"
  # - XCODE_SCHEME="Unlinked tests macos" DESTINATION="platform=macOS"
script: bash -c "xcodebuild test -project PrivateProtocolBuffer.xcodeproj -scheme $XCODE_SCHEME -destination $DESTINATION"

matrix:
  include:
    - env: XCODE_SCHEME="Linked\\ tests\\ ios" DESTINATION="platform=iOS\\ Simulator,name=iPhone\\ 8"
      osx_image: xcode9.4

    - env: XCODE_SCHEME="Linked\\ tests\\ macos" DESTINATION="platform=macOS"
      osx_image: xcode9.4
